schema_version = 1
id = "runt"
name = "Runt"
version = "0.1.0"
description = "Runt language support"
authors = ["thejunt"]
repository = "https://github.com/runt-lang/runt-zed"

[grammars.runt]
repository = "https://github.com/runt-lang/runt-treesitter"
rev = "7454014f3b4dfcf1a4a599755d72479011660929"

[language_servers.runtc-lsp]
name = "runtc-lsp"
languages = ["Runt"]
