schema_version = 1
id = "runt"
name = "Runt"
version = "0.1.0"
description = "Runt language support"
authors = ["thejunt"]
repository = "https://github.com/runt-lang/runt-zed"

[grammars.runt]
repository = "https://github.com/runt-lang/runt-treesitter"
rev = "00794cfb2c2b786f2a80416202cfeabc6c2edaf1"

[language_servers.runtc-lsp]
name = "runtc-lsp"
languages = ["Runt"]
